### ISSUE TITLE
AAA this is a test lmao

### ISSUE THREAD

**Issue by tognols** [ztdlib/filesystem#6]
There is no issue

**Comment by tognols** [comment]
Test

**Comment by tognols** [comment]
Ok so, since I'm not able to delete this test issue (the button for deleting issues is no more) this is NOT how to use Github.

**Comment by LynxesExe** [comment]
Locked as "too heated" LMAOOO

**Comment by LynxesExe** [comment]
Admin boiz be like writing on locked stuff
